services:
  bionic:
    command: |
      sh -c 'cp -r /root/output/* /output/'
    environment:
      - R_VERSION=${R_VERSION:?error}
    build:
      context: .
      dockerfile: dockerfiles/bionic/Dockerfile
      args:
        R_VERSION: ${R_VERSION:?error}
      target: ${TARGET-package}
    image: r-hub/r-glibc-bionic
    volumes:
      - ./output:/output

  test:
    command: |
      TODO
    build:
      context: .
      dockerfile: dockerfiles/test/Dockerfile
      args:
        CONTAINER: ${CONTAINER:-r-hub/failure/here}
    volumes:
      - .:/root
