services:
  bionic:
    command: /package.sh
    environment:
      - R_VERSION=${R_VERSION}
    build:
      context: .
      dockerfile: dockerfiles/bionic/Dockerfile
      args:
        R_VERSION: ${R_VERSION}
    image: r-hub/r-glibc-bionic
    volumes:
      - ./output:/output
